# Define anchor for common docker configuration
x-docker-config: &docker-config
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    DOCKER_HOST: ${DOCKER_HOST:-unix:///var/run/docker.sock}

services:
  data-pipeline:
    <<: *docker-config

  airflow-webserver:
    <<: *docker-config

  airflow-worker:
    <<: *docker-config

  airflow-scheduler:
    <<: *docker-config
