version: '2.32.4'

services:
  data-pipeline:
    build:
      context: ./Data-Pipeline 
      dockerfile: Dockerfile
    container_name: data-pipeline-container
    volumes:
     - ./Data-Pipeline/scripts:/app/scripts
    working_dir: /app/scripts
    command: python main.py
    restart: always