name: Data-Pipeline

on:
  push:
    branches:
      - data-pipeline-deployment

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install unittest

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/Data_Pipeline" >> $GITHUB_ENV

      - name: Run Unittest
        run: python -m unittest discover -s tests -p "test*.py"

  docker-compose:
    name: Run Docker Compose
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Load Environment Variables
        run: |
          echo "AIRFLOW_UID=50000" >> $GITHUB_ENV
          echo "DOCKER_GID=1000" >> $GITHUB_ENV

      - name: Start Docker Compose
        run: docker-compose up -d --build

      # - name: Wait for Services to Start
      #   run: sleep 30  

      - name: Verify Containers are Running
        run: docker ps -a
